version: '3.1'
services:
    php-fpm:
        build: .docker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './.docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        env_file:
            - .env