name: CI

on: [push, workflow_dispatch]

jobs:
  psalm:
    name: psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring
          ini-values: max_execution_time=600, memory_limit=-1
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Validate composer.json
        run: composer validate

      - name: Run Unit Tests
        run: composer unit-tests

      - name: Run CS Fixer
        run: composer style-fix

      - name: Run psalm
        run: ./vendor/bin/psalm --output-format=github
